baseURL: "https://roni.io/"
languageCode: "en-us"
title: "Roni Gorodetsky - Full-stack IoT developer and Entrepreneur"
theme: hugo-profile

Paginate: 3
disqusShortname: roni-io
googleAnalytics: G-CV897YSFYR

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

params:
  title: ""
  images:
    - /images/hero.jpeg
  description: "Roni Gorodetsky - an Entrepreneur and full-stack IoT developer with experience in hardware, mobile development, cyber security, cloud and firmware."
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.ico"
  applefavicon: "/images/favicon.ico"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # uncomment to make it dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Full-stack IoT developer and Entrepreneur, my name is"
    title: "Roni Gorodetsky"
    subtitle: "And I get things done."
    content: "A passionate Full-stack IoT developer and Entrepreneur. I use modern frameworks, cutting edge tools and hardware to turn ideas into reality."
    image: /images/hero.jpeg
    button:
      enable: true
      name: "Resume"
      url: "https://www.linkedin.com/in/roni-gorodetsky/"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Zontex/
        - icon: fab fa-twitter
          url: https://twitter.com/roni_gorodetsky
      #customIcons:
      #  - icon: /fav.png
      #    url: "https://roni.io/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "images/cat-computer.webp"
    content: |-
      I am a full-stack IoT developer with experience in hardware, mobile development, cyber security, cloud and firmware with ability to communicate in English, Hebrew, Russian, and Mandarin.<br/><br/>Extremely passionate about hardware and web3 decentralization ideas. on my free time I love to explore new project ideas and see how I can take an idea, make a plan and finally turn it into reality. The more projects I explore, the bigger my skillset gets. I'm a strong believer in project-based learning.<br/><br/>
    skills:
      enable: true
      title: "Some of the technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "React-native"
        - "Python3"
        - "MicroPython"
        - "C"
        - "C++"
        - "Raspberry Pi"
        - "Arduino"
        - "ESP32"
        - "Sails.js"
        - "Mongodb"
        - "MySQL"
        - "PostgreSQL"
        - "PHP"
        - "Electron"

  # Experience, we have linkedin for that
  experience:
    enable: false
    items:
      - job: ""
        company: ""
        companyUrl: ""
        date: ""
        featuredLink:
          enable: true
          name: ""
          url: ""
        content: ""

  # Education, we have linkedin for that
  education:
    enable: false
    items:
      - title: ""
        school:
          name: ""
          url: ""
        date: ""
        GPA: ""
        content: |-
         text
         
  # Achievements
  achievements:
    enable: true
    items:
      - title: Innovator of the year
        content: Issued by Beijing Chaoyang district government 
        url: '#'
      - title: Shenzhen Entrepreneur star
        content: Nanshan government Shenzhen Entrepreneur star contest finalist
        url: '#'
      - title: Smarthon Hackthon Grand Winner
        content: Won the grand prize of 50,000HKD in Smarton hackathon which held in Hong Kong by developing a smart IoT solution within 30 hours limit.
        url: '#'
      - title: DJI Bug bounty responsible disclosure
        content: found a critical vulnerability that affected all DJI cloud users, the bug been acknowledged and fixed as part of the DJI bug bounty program.
        url: '#'
      - title: Instagram vulnerability disclosure
        content: Reported an authorization bypass / Information disclosure exploited in the wild, the security problem reported to Kaspersky Security Researche which worked directly with Facebook in order to resolve it.
        url: '#'

  # projects
  projects:
    enable: true
    items:
      - title: PETRACK Smart bag dispenser
        content: an IoT environmental friendly and solar powered bag dispenser designed for smart cities and property managers.
        image: images/projects/petrack-smart-dog-bag-dispenser.png
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "PETRACK"
           - "IoT"
           - "Smart bag dispenser"
           - "dog bag dispenser"
      
      - title: Binnovate smart bottle recycling machine
        content: Designed an invention of smart recycling device suitable for Israeli plastic bottles "cages", can scan the bottle QR code in 360 degrees and detect the type of bottle dispensed and it's owner.
        image: images/projects/binnovate-smart-recycling-bin.png
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "Binnovate"
           - "IoT"
           - "Bottle recycling"
           - "IoT environment solution"
      
      - title: World's first Raspberry Pi Laptop - CrowPi
        content: I am the guy behind the CrowPi invention, from idea to reality, I managed a team of engineers at Elecrow to bring this idea to the masses. 
        image: images/projects/elecrow-crowpi2-laptop.webp
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "CrowPi"
           - "Raspberry Pi Laptop"
           - "DIY Learning"
        links:
          - icon: fa fa-globe
            url: 'https://www.kickstarter.com/projects/elecrow/crowpi-lead-you-go-from-zero-to-hero-with-raspberr'
      
      - title: Eduponics Mini - STEM Agriculture kit
        content: I funded STEMinds.com to create cutting edge hardware kits for education, Eduponics was designed to teach people of all ages about smart agriculture, IoT and sustainability.
        image: 'images/projects/steminds-eduponics-mini-exhibition.webp'
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "Eduponics"
           - "Smart agriculture"
           - "IoT"
           - "ESP32"
        links:
          - icon: fa fa-globe
            url: https://www.crowdsupply.com/steminds/eduponics-mini
      
      - title: Edge Smart inventory management with smart LEDs
        content: I designed a smart edge inventory management system, based on the open source "Inventree" project, the system enables locating components with ease using smart LEDs and instantly print labels by connecting to a wireless/wired label printer.
        image: 'images/projects/omnikit-smart-inventory-leds.png'
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "Inventory management"
           - "Inventory smart LEDs"
           - "Smart logistics"
           - "Edge inventory"
        links:
          - icon: fa fa-globe
            url: https://www.hackster.io/news/this-raspberry-pi-powered-inventory-tracker-means-you-ll-never-misplace-a-component-again-3f70856a97f5

      - title: OmniKit - Edge modular IoT gateway
        content: "Modular, stackable edge IoT gateway that enables complete control over both indoor and outdoor infrastructure and devices. features include: solar power, UPS, watchdog timer, PoE, 4G-LTE, LoRaWAN, NVMe-SSD and much more."
        image: 'images/projects/omnikit-edge-gateway.jpeg'
        #featured:
        #  name: text
        #  link: '#'
        badges:
           - "IoT"
           - "IoT edge device"
           - "Smart IoT gatway"
           - "Smart agriculture"
           - "Smart home"
        links:
          - icon: fa fa-globe
            url: https://omniot.io/

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: roni@roni
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Zontex/
      linkedin: https://www.linkedin.com/in/roni-gorodetsky/
      twitter: https://twitter.com/roni_gorodetsky
      instagram: https://instagram.com/roni.gorodetsky

# add robots.txt
enableRobotsTXT: true
# add sitemap
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5